# Generated by Django 6.0 on 2025-12-20 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uigdpro', '0002_githubrun_direction_githubrun_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrun',
            options={'verbose_name': 'GitHub Build Run', 'verbose_name_plural': 'GitHub Build Runs'},
        ),
        migrations.AddField(
            model_name='githubrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrun',
            name='platform',
            field=models.CharField(choices=[('windows', 'Windows (64-bit)'), ('windows-x86', 'Windows (32-bit)'), ('linux', 'Linux'), ('macos', 'macOS'), ('android', 'Android')], default='github', help_text='Target OS/platform for the build', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='direction',
            field=models.CharField(help_text="Connection type: 'direct' or 'relay'", max_length=20),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='filename',
            field=models.CharField(help_text="Custom executable name (e.g., 'mydesk.exe')", max_length=255),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Success', 'Success'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='InProgress', help_text='Current status of the GitHub Action workflow', max_length=20),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='uuid',
            field=models.CharField(help_text='UUID used to identify the build and associated assets (PNGs, EXE, etc.)', max_length=36, unique=True),
        ),
        migrations.AddIndex(
            model_name='githubrun',
            index=models.Index(fields=['uuid'], name='uigdpro_git_uuid_b41b27_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrun',
            index=models.Index(fields=['status'], name='uigdpro_git_status_a22dae_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrun',
            index=models.Index(fields=['platform'], name='uigdpro_git_platfor_bd3f98_idx'),
        ),
    ]
