# Generated by Django 6.0 on 2025-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='direction',
            field=models.CharField(default='both', max_length=100),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='filename',
            field=models.CharField(default='rustdesk', max_length=255),
        ),
    ]
